param(
  [string]$Destination = "$PSScriptRoot/../data/external"
)

$ErrorActionPreference = 'Stop'
$url = 'https://data.openei.org/files/910/Data%20Sets%20for%20AFDD%20Evauluation%20of%20Building%20FDD%20Algorithms.zip'
$zip = Join-Path $Destination 'oedi910.zip'
$extract = Join-Path $Destination 'oedi910_extract'
New-Item -ItemType Directory -Force $Destination | Out-Null
Invoke-WebRequest -UseBasicParsing -Uri $url -Headers @{ 'User-Agent' = 'Nengzhihe-reproducibility-script/1.0' } -OutFile $zip
Expand-Archive -LiteralPath $zip -DestinationPath $extract -Force
$source = Join-Path $extract 'MZVAV-2-1.csv'
if (-not (Test-Path -LiteralPath $source)) { throw 'OEDI archive did not contain MZVAV-2-1.csv' }
Write-Host "Downloaded physical MZVAV-2-1 source to $source"
Write-Host (Get-FileHash -Algorithm SHA256 -LiteralPath $zip | Format-Table -HideTableHeaders | Out-String).Trim()
Write-Host (Get-FileHash -Algorithm SHA256 -LiteralPath $source | Format-Table -HideTableHeaders | Out-String).Trim()
Write-Host 'The tracked subset is generated by selecting the six dates in external_physical.py; labels and fault dates must remain outside the diagnostic input.'
