s = open('make_fig.py', encoding='utf-8').read()
R = [
 ('SANS = "Inter, \'Helvetica Neue\', Arial, sans-serif"', 'SANS = "Inter, \'Noto Sans CJK SC\', \'Microsoft YaHei\', \'PingFang SC\', sans-serif"'),
 ('    w = len(s) * size * 0.56 + 14', '    w = vis(s, size) + 14'),
 ('    w = w or len(s) * 6.9 + 18', '    w = w or vis(s, 11.5) + 18'),
 ('def label_pill(', 'def vis(s, size):\n    return sum(size * (1.0 if ord(ch) > 0x2E80 else 0.56) for ch in s)\n\ndef label_pill('),
 ('aria-label="Framework of Nengjiandu: multi-source inputs feed a physics-based hourly simulation, decision analytics and a decision interface, closed by a human-in-the-loop local-LLM interface."',
  'aria-label="能见度方法框架：多源输入经物理逐时仿真、决策分析进入决策界面，并由人机协同的本地大模型交互层形成闭环。"'),
 ("Human-in-the-loop language interface", "人机协同的自然语言交互"),
 ('"re-planning loop runs right → left"', '"重规划闭环：自右向左"'),
 ('"Decision maker"', '"决策者"'),
 ('"Natural-language request"', '"用自然语言提出需求"'),
 ('"“3 units per room,"', '"“每间改 3 台，"'),
 ('" no grid export”"', '"  多余电不卖给电网”"'),
 ('"Local LLM (on-premise)"', '"本地大模型（离线部署）"'),
 ('"Tool-calling under a strict JSON schema"', '"在严格 JSON 模式下调用工具"'),
 ('"Edits task fields only — never emits results"', '"只修改任务字段，从不输出计算结果"'),
 ('"No data leaves the machine"', '"数据不出本机"'),
 ('"Proposed edits ΔΘ"', '"修改建议 ΔΘ"'),
 ('[("field: ", ""), ("from", "i"), (" → ", ""), ("to", "i"), ("   (validated against API ranges)", "")]',
  '[("字段：", ""), ("原值", "i"), (" → ", ""), ("新值", "i"), ("（按接口取值范围校验）", "")]'),
 ('"Unsupported items listed, not dropped"', '"不支持的内容逐条列出，不静默丢弃"'),
 ('"Ambiguity → clarification question"', '"表述不清 → 反问澄清"'),
 ('"User confirmation"', '"用户确认"'),
 ('"Accept / revise proposed edits"', '"采用或修改建议"'),
 ('[("→ structured task ", ""), ("Θ", "mi")]', '[("→ 结构化任务 ", ""), ("Θ", "mi")]'),
 ('"(room, AC, PV, wind, tariff, quotes)"', '"（房间、空调、光伏、风机、电价、报价）"'),
 ('"task Θ"', '"任务 Θ"'),
 ('"inspect / revise"', '"查看 / 调整"'),
 ('"Multi-source inputs"', '"多源输入"'),
 ('("Hourly weather", ["Reanalysis, 8,784 h (2024)", "Air temp., RH, pressure, irradiance, wind", "Interval semantics normalised"])',
  '("逐时气象", ["再分析数据，8,784 h（2024 年）", "气温、湿度、气压、辐照、风速", "时段语义统一处理"])'),
 ('("Building & HVAC", ["Room geometry, envelope, schedule", "AC catalog: rated capacity, COP", "N rooms × n units per room"])',
  '("建筑与空调", ["房间尺寸、围护结构、使用时段", "空调目录：额定制冷量、COP", "N 间房 × 每间 n 台"])'),
 ('("Site & equipment", ["Roof area → PV capacity bound", "Certified small-wind power curve", "User quotes: PV, wind, storage"])',
  '("场地与设备", ["屋顶面积 → 光伏容量上限", "认证小风机功率曲线", "用户报价：光伏、风机、储能"])'),
 ('("Policy & market", ["Official 4-period TOU tariff", "Critical peak: Jul–Sep, Tmax ≥ 35 °C", "Grid EF 0.4419 kgCO₂/kWh (GD)"])',
  '("政策与市场", ["官方四段分时电价", "尖峰：7–9 月及日最高温 ≥ 35 °C", "广东电网排放因子 0.4419 kgCO₂/kWh"])'),
 ('"Physics-based hourly simulation"', '"物理驱动的逐时仿真"'),
 ('"Lumped RC heat–moisture room model"', '"集总 RC 房间热湿模型"'),
 ('("     sensible + latent,  ", "")', '("     显热 + 潜热，  ", "")'),
 ("'<tspan font-weight=\"650\" fill=\"#1D5FA8\">Comfort-gated sizing</tspan>  ·  60-min pre-cooling (energy counted)'",
  "'<tspan font-weight=\"650\" fill=\"#1D5FA8\">舒适度约束选台</tspan>  ·  上班前预冷 60 分钟（预冷用电计入）'"),
 ('"Shortfall & unmet temperature/RH scored in occupied hours only"', '"冷量不足与温湿度未达标只在使用时段判定"'),
 ('[("Unit sweep ", ""),', '[("台数比选 ", ""),'),
 ('(" : shortfall = 0 }", "m"), ("   (min. adequate units)", "")', '(" : 冷量不足 = 0 }", "m"), ("  （最少达标台数）", "")'),
 ('("PV generation", "pvlib (PVWatts) · POA transposition", "Cell temperature from air temp. & wind", "Capacity bounded by roof area")',
  '("光伏发电", "pvlib（PVWatts）· 斜面辐照换算", "由气温与风速计算组件温度", "容量受屋顶面积约束")'),
 ('("Wind generation", "Certified SD6 power curve", "Hub-height speed (Hellman law):", None)',
  '("风力发电", "SD6 认证功率曲线", "轮毂高度风速（Hellman 幂律）：", None)'),
 ('"Hourly energy matching"', '"逐时能量匹配"'),
 ('"self-use · grid import · surplus"', '"自用 · 电网购电 · 余电"'),
 ('"vs. conventional annual estimate"', '"对比：传统全年粗算"'),
 ('("  (ignores timing & TOU)", "")', '("（忽略时间错配与分时电价）", "")'),
 ('"pre-cool"', '"预冷"'),
 ('("#2F9E6B", "self-use s"), ("#E8A33D", "surplus"), ("#9AA5B1", "import")', '("#2F9E6B", "自用 s"), ("#E8A33D", "余电"), ("#9AA5B1", "购电")'),
 ('"Decision analytics"', '"决策分析"'),
 ('"Scenario & capacity sweep"', '"方案与容量比选"'),
 ('["S0 grid only", "S1 PV", "S2 wind", "S3 PV + wind"]', '["S0 只用电网", "S1 光伏", "S2 风机", "S3 风光组合"]'),
 ('[("PV capacity ", ""), ("k", "mi"), (" ∈ ", "m"), ("K", "mi"), (" (roof-bounded);  S0 kept as baseline", "")]',
  '[("光伏容量 ", ""), ("k", "mi"), (" ∈ ", "m"), ("K", "mi"), ("（受屋顶约束）；S0 始终作为基准", "")]'),
 ('"TOU-aware lifecycle economics"', '"分时电价下的全生命周期经济性"'),
 ('"p(t): valley / flat / peak / critical-peak by hour, month and daily Tmax"', '"p(t)：按小时、月份和日最高温取谷 / 平 / 峰 / 尖峰电价"'),
 ('[("Outputs: 10-yr total cost, ", ""), ("Δ", "m"), ("TC", "mi"), (" vs. S0 (sign kept), simple payback", "")]',
  '[("输出：10 年总花费、相对 S0 的 ", ""), ("Δ", "m"), ("TC", "mi"), ("（保留正负）、简单回本年限", "")]'),
 ('"Carbon accounting"', '"碳排放核算"'),
 ('"Official provincial factor; carbon price shown as a scenario only"', '"采用官方省级排放因子；碳价仅作情景展示"'),
 ('"Surplus valorisation (add-on paths)"', '"余电利用（附加路径）"'),
 ('"Storage: rule-based dispatch, η = 0.90 → investment, payback"', '"储能：规则调度，η = 0.90 → 投入与回本"'),
 ('"Grid export: rough revenue from the same surplus"', '"卖给电网：同一份余电的收入粗算"'),
 ('"not added to the main ranking"', '"不计入主方案排序"'),
 ('"Constraint-aware status & recommendation"', '"约束感知的状态判定与推荐"'),
 ('["feasible", "over budget", "quote unknown", "service gap"]', '["可行", "超预算", "报价未知", "冷量缺口"]'),
 ('[("Recommend ", ""), ("argmin", "m"), (" TC", "mi"), (" over comparable candidates;", "")]',
  '[("在可比较方案中取 ", ""), ("argmin", "m"), (" TC", "mi"), (" 作为推荐；", "")]'),
 ('"unknown ≠ excluded; service gap never shown as adequate"', '"条件不全 ≠ 淘汰；有冷量缺口绝不显示为达标"'),
 ('"hourly flows"', '"逐时电量"'),
 ('"tariff p(t), emission factor, quotes"', '"电价 p(t)、排放因子、报价"'),
 ('"Decision interface"', '"决策界面"'),
 ('"Progressive computing"', '"渐进式计算"'),
 ('"Typical-week preview"', '"典型周预览"'),
 ('"physics only, < 1 s"', '"仅物理匹配，< 1 秒"'),
 ('"Full-year async job"', '"全年后台计算"'),
 ('"real backend progress"', '"显示真实进度"'),
 ('"Visual evidence"', '"可视化证据"'),
 ('"Energy calendar (month × hour)"', '"能源日历（月 × 小时）"'),
 ('"Capacity–cost curve (best marked)"', '"容量—花费曲线（标出最优）"'),
 ('"10-yr ledger · carbon · storage"', '"10 年总账 · 减碳 · 储能"'),
 ('"Hourly CSV / JSON / printable brief"', '"逐时 CSV / JSON / 可打印简报"'),
 ('"Accountable output"', '"可追溯的输出"'),
 ('"Every number from computation"', '"每个数字都来自计算"'),
 ('"Edits invalidate stale results"', '"改条件即令旧结果失效"'),
 ('"Saved plans side-by-side"', '"保存的方案可并排对比"'),
 ('"Sources & hashes traceable"', '"来源与哈希可追溯"'),
 ('"results"', '"结果"'),
 ('"Key contributions"', '"主要创新点"'),
 ('("C1", "Hourly coupling", "Load, PV and wind matched hour-by-hour under TOU prices, instead of annual energy × average price.")',
  '("C1", "逐时耦合", "负荷、光伏与风电按小时匹配并按分时电价计费，|取代“年发电量 × 平均电价”的粗算。")'),
 ('("C2", "Comfort-gated sizing", "AC load and unit count derived from heat–moisture physics with an explicit adequacy rule.")',
  '("C2", "舒适度约束选台", "空调负荷与台数由热湿物理模型和明确的|达标规则共同确定。")'),
 ('("C3", "Policy-faithful economics", "Official tariff incl. temperature-triggered critical peak, lifecycle costs and provincial carbon factor.")',
  '("C3", "贴合政策的经济性", "官方电价（含高温触发尖峰）、全生命周期|费用与省级排放因子。")'),
 ('("C4", "Honest decision semantics", "Unknown ≠ excluded; service gaps flagged; grid-only baseline always kept for comparison.")',
  '("C4", "诚实的决策语义", "条件不全不等于淘汰；冷量缺口必须标出；|“只用电网”始终保留作对比基准。")'),
 ('("C5", "LLM as interface, not calculator", "On-premise LLM turns language into validated task edits; deterministic tools compute every number.")',
  '("C5", "大模型做界面，不做计算器", "本地大模型把自然语言转成经校验的任务修改；|所有数字由确定性程序计算。")'),
 ('("C6", "渐进式计算", "Sub-second typical-week preview, then a full-year job with real progress for interactive use.")',
  '("C6", "渐进式计算", "秒级典型周预览，随后全年后台计算并显示|真实进度，支持交互式使用。")'),
 ('    words = d.split(); lines = [""]\n', '    lines = d.split("|") if "|" in d else [d]\n    words = []\n'),
 ('scratchpad/fig/framework.svg"', 'scratchpad/fig/framework_zh.svg"'),
]
for a, b in R:
    assert a in s, a[:70]
    s = s.replace(a, b)
open('make_fig_zh.py', 'w', encoding='utf-8').write(s)
print("ok")
